### ISSUE TITLE
após o login, em alguns momentos o usuário está sendo redirecionado para rota home, que não existe

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/eventos#13]

**Comment by masakik** [comment]
Achei que eu havia criado uma issue sobre isso. Parece que se o servidor está 'inativo' algum tempo ele dá a mensagem de erro. Ao recarregar a página ele carrega normal. Não sei se é o mesmo que isso.

**Comment by masakik** [comment]
No meu caso isso ocorre antes de aparecer qualquer coisa na tela.

**Comment by thiagogomesverissimo** [comment]
Normalmente aquele print que você mandou está relacionado a rota inexistente, mas como no print não tem a url não da para saber. Se ocorrer, mande a url que dá o erro. Pois não consigo reproduzir.
