### ISSUE TITLE
Mind Map inicial sobre o sistema

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/eventos#8]
![eventosmindmap](https://user-images.githubusercontent.com/10613364/40186404-5f4f62f8-59cb-11e8-9470-2c65d13279b2.png)

**Comment by alecostaweb** [comment]
Alguma semelhança com processo seletivo?

**Comment by masakik** [comment]
Ola, você diz processo seletivo de ingresso numa pós por exemplo? Acho que poderia ser aplicado para esse caso sim.

**Comment by masakik** [comment]
Mas aí não chamaria eventos, seria algo tipo "inscreve". Para o evento propriamente haveria as listas de presença, certificados, crachás e poderia haver outros elementos tipo: 
- salas e as respectivas atividades em cada uma, 
- o tipo de certificado (apresentador, ouvinte, staff)
- se apresentador (oral, poster, minicurso, etc)
Bom, imagino uma série de possibilidades ligadas diretamente ao evento em si.
Sem contar a parte de análise de mérito dos trabalhos.

**Comment by masakik** [comment]
Aliás o ojs peca nessa parte do evento. Ele é forte na análise dos trabalhos, reviews, etc mas não tem nada dessa parte do evento que descrevi aqui. Se eu estive errado alguém me corrija.

**Comment by alecostaweb** [comment]
Sim, @masakik quanto ao nome do sistema também fico na dúvida, mas com relação a modalidade ou finalidade, acredito que podemos adicionar processo seletivo com todos seus requisitos.

**Comment by thiagogomesverissimo** [comment]
Como start usei esse repo no [https://subscriptions.uspdev.fflch.usp.br/](https://subscriptions.uspdev.fflch.usp.br/), mas falta muito para implementarmos esse mindmap. Talvez como essa primeira versão minimalista já conseguimos criar issues menores.
